// Sentence calculation engine with detailed breakdown export.
import { sanitizeNumber } from './sanitize.js';
export function clamp(v,min,max){return Math.max(min,Math.min(max,v));}
export function calculateReportTotals(charges, context={numPriors:0, recidiveCodes:new Set(), comboRules:[]}){
  const breakdown=[]; let totalFine=0; let totalMonths=0;
  charges.forEach((charge,index)=>{
    const baseFine=sanitizeNumber(charge.base_fine); const minFine=sanitizeNumber(charge.min_fine); const maxFine=sanitizeNumber(charge.max_fine);
    const priors=context.numPriors||0; let finePriors=baseFine*(1+0.25*priors);
    if(context.recidiveCodes && context.recidiveCodes.has(charge.code)){finePriors*=sanitizeNumber(charge.recidive_multiplier||1);}
    const clampedFine=clamp(finePriors,minFine,maxFine); totalFine+=clampedFine;
    let months=sanitizeNumber(charge.base_months)+Math.floor(priors*sanitizeNumber(charge.months_per_prior||0)); totalMonths+=months;
    breakdown.push({type:'charge',index,code:charge.code,baseFine,finePriors,clampedFine,months});
  });
  (context.comboRules||[]).forEach(rule=>{const ok=rule.requires.every(code=>charges.some(c=>c.code===code)); if(ok){const addFine=totalFine*(rule.fineMultiplier-1); const addMonths=Math.floor(totalMonths*(rule.monthsMultiplier-1)); totalFine+=addFine; totalMonths+=addMonths; breakdown.push({type:'combo',reason:rule.reason,addFine,addMonths});}});
  return { total_fine:Math.round(totalFine), total_months:Math.round(totalMonths), breakdown };}
// Calculator note 001: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 002: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 003: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 004: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 005: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 006: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 007: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 008: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 009: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 010: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 011: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 012: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 013: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 014: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 015: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 016: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 017: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 018: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 019: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 020: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 021: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 022: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 023: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 024: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 025: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 026: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 027: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 028: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 029: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 030: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 031: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 032: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 033: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 034: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 035: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 036: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 037: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 038: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 039: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 040: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 041: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 042: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 043: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 044: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 045: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 046: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 047: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 048: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 049: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 050: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 051: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 052: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 053: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 054: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 055: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 056: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 057: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 058: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 059: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 060: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 061: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 062: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 063: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 064: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 065: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 066: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 067: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 068: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 069: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 070: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 071: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 072: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 073: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 074: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 075: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 076: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 077: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 078: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 079: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 080: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 081: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 082: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 083: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 084: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 085: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 086: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 087: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 088: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 089: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 090: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 091: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 092: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 093: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 094: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 095: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 096: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 097: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 098: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 099: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 100: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 101: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 102: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 103: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 104: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 105: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 106: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 107: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 108: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 109: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 110: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 111: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 112: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 113: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 114: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 115: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 116: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 117: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 118: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 119: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 120: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 121: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 122: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 123: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 124: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 125: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 126: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 127: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 128: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 129: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 130: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 131: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 132: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 133: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 134: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 135: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 136: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 137: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 138: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 139: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 140: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 141: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 142: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 143: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 144: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 145: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 146: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 147: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 148: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 149: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 150: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 151: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 152: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 153: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 154: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 155: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 156: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 157: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 158: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 159: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 160: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 161: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 162: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 163: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 164: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 165: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 166: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 167: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 168: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 169: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 170: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 171: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 172: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 173: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 174: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 175: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 176: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 177: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 178: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 179: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 180: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 181: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 182: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 183: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 184: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 185: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 186: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 187: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 188: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 189: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 190: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 191: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 192: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 193: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 194: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 195: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 196: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 197: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 198: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 199: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 200: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 201: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 202: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 203: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 204: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 205: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 206: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 207: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 208: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 209: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 210: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 211: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 212: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 213: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 214: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 215: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 216: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 217: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 218: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 219: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
// Calculator note 220: adjust legal coefficients carefully and sync with server-side Lua calculator to avoid divergence.
